pep_version: 2.0.0
sample_table: "sample_table.csv"
sample_modifiers:
  derive:
    attributes: [l1r1, l1r2, l2r1, l2r2]
    sources:
      sourcenull: " "
      source1: "data/reads2/CE7LPANXX-{ogf_lib_id}_S{sample_number}_L002_R1_001.fastq.gz"
      source2: "data/reads2/CE7LPANXX-{ogf_lib_id}_S{sample_number}_L003_R2_001.fastq.gz"
      source3: "data/reads2/CE7LPANXX-{ogf_lib_id}_S{sample_number}_L003_R1_001.fastq.gz"
      source4: "data/reads2/CE7LPANXX-{ogf_lib_id}_S{sample_number}_L002_R2_001.fastq.gz"
      source5: "data/reads1/{sample_number}_R1.fastq.gz"
      source6: "data/reads1/{sample_number}_R2.fastq.gz"
