pep_version: 2.0.0
sample_table: "sample_table.csv"
sample_modifiers:
  imply:
    - if:
        group: "castes"
      then:
        derive:
          attributes: [r1, r2]
          sources:
            data1: "data/reads/{sample_number}_R1.fastq.gz"
            data2: "data/reads/{sample_number}_R2.fastq.gz"
    - if:
        group: "angry"
      then:
        derive:
          attributes: [l2r1, l2r2, l3r1, l3r2]
          sources:
            data1: "data/reads/CE7LPANXX-{ogf_lib_id}_S{ogf_sample_number}_L002_R1_001.fastq.gz"
            data2: "data/reads/CE7LPANXX-{ogf_lib_id}_S{ogf_sample_number}_L002_R2_001.fastq.gz"
            data3: "data/reads/CE7LPANXX-{ogf_lib_id}_S{ogf_sample_number}_L003_R1_001.fastq.gz"
            data4: "data/reads/CE7LPANXX-{ogf_lib_id}_S{ogf_sample_number}_L003_R2_001.fastq.gz"
